# Rename this file to languages.toml to enable multilingual support

[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "001eander 的博客"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "001eander's Blog"
weight = 2
