# Configure main menu and social menu

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/001eander"

[social.params]
icon = "brand-github"

[[social]]
identifier = "zhihu"
name = "知乎"
url = "https://www.zhihu.com/people/oleander-15-8"

[social.params]
icon = "brand-zhihu"
